parameters:
- name: pathToSolutionFolder
  type: string
- name: buildContext
  type: string
- name: releaseName
  type: string
- name: environment
  type: string
- name: acrUrl
  type: string
- name: acrServiceConnection
  type: string

stages:
- stage: DockerBuildPush
  displayName: 'Build and Push Docker Image'
  dependsOn: BuildAndTest
  condition: succeeded()
  jobs:
  - job: DockerBuildPush
    displayName: 'Build and Push to ACR'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self

    - task: Docker@2
      displayName: 'Build Docker Image'
      inputs:
        command: 'build'
        containerRegistry: '${{ parameters.acrServiceConnection }}'
        repository: '${{ parameters.environment }}/${{ parameters.releaseName }}'
        dockerfile: '${{ parameters.pathToSolutionFolder }}/Dockerfile'
        buildContext: ${{ parameters.buildContext }}
        tags: |
          $(Build.BuildNumber)
          ${{ parameters.environment }}-latest

    - task: Docker@2
      displayName: 'Push Docker Image to ACR'
      inputs:
        command: 'push'
        containerRegistry: '${{ parameters.acrServiceConnection }}'
        repository: '${{ parameters.environment }}/${{ parameters.releaseName }}'
        tags: |
          $(Build.BuildNumber)
          ${{ parameters.environment }}-latest
