parameters:
- name: releaseName
  type: string
- name: environment
  type: string
- name: pathToSolutionFolder
  type: string
- name: acrUrl
  type: string
- name: k8sServiceConnection
  type: string
- name: requiresApproval
  type: boolean
  default: false
- name: secureYml
  type: string
  default: ''

stages:
- stage: HelmDeploy_${{ parameters.environment }}
  displayName: 'Deploy to AKS - ${{ upper(parameters.environment) }}'
  dependsOn: DockerBuildPush
  condition: succeeded()
  ${{ if eq(parameters.requiresApproval, true) }}:
    pool: server
  jobs:
  - ${{ if eq(parameters.requiresApproval, true) }}:
    - job: WaitForValidation
      displayName: 'Approval Gate - Production Deployment'
      pool: server
      timeoutInMinutes: 1440
      steps:
      - task: ManualValidation@0
        inputs:
          notifyUsers: ''
          instructions: 'Review and approve deployment to production'
          onTimeout: 'reject'

  - deployment: HelmDeploy_${{ parameters.environment }}
    displayName: 'Helm Deploy to ${{ upper(parameters.environment) }}'
    ${{ if eq(parameters.requiresApproval, true) }}:
      dependsOn: WaitForValidation
      condition: succeeded()
    pool:
      vmImage: 'ubuntu-latest'
    environment: '${{ parameters.environment }}'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          - ${{ if ne(parameters.secureYml, '') }}:
            - task: DownloadSecureFile@1
              name: DownloadSecureYml
              displayName: 'Download secure values file'
              inputs:
                secureFile: ${{ parameters.secureYml }}

          - task: HelmDeploy@1
            displayName: 'Helm Upgrade Release'
            inputs:
              connectionType: 'Kubernetes Service Connection'
              kubernetesServiceConnection: ${{ parameters.k8sServiceConnection }}
              command: 'upgrade'
              chartType: 'FilePath'
              chartPath: './shared/helm-charts/plain-app-chart'
              releaseName: ${{ parameters.releaseName }}
              install: true
              waitForExecution: true
              namespace: ${{ parameters.environment }}
              arguments: '--create-namespace'
              valueFiles: |
                ${{ parameters.pathToSolutionFolder }}/values.yaml
                ${{ if ne(parameters.secureYml, '') }}:$(DownloadSecureYml.secureFilePath)
              overrideValues: 'image.repository=${{ parameters.acrUrl }}/${{ parameters.releaseName }},image.tag=$(Build.BuildNumber),environment=${{ parameters.environment }}'

          - bash: |
              echo "=========================================="
              echo "✅ Deployment to ${{ upper(parameters.environment) }} Successful"
              echo "=========================================="
              echo "Release: ${{ parameters.releaseName }}"
              echo "Environment: ${{ parameters.environment }}"
              echo "Image: ${{ parameters.acrUrl }}/${{ parameters.environment }}/${{ parameters.releaseName }}:$(Build.BuildNumber)"
              echo "=========================================="
            displayName: 'Deployment Summary'
