parameters:
- name: solutionName
  type: string
- name: pathToSolutionFolder
  type: string
- name: buildContext
  type: string
- name: buildConfiguration
  type: string
  default: 'Release'
- name: serviceType
  type: string
  default: 'dotnet'  # 'dotnet' or 'python'

stages:
- stage: PRValidation
  displayName: 'PR Validation - Build and Test'
  jobs:
  - job: ValidateDotNetService
    displayName: 'Validate .NET Service'
    condition: eq('${{ parameters.serviceType }}', 'dotnet')
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '8.x'
        installationPath: $(Agent.ToolsDirectory)\dotnet
        
    - task: DotNetCoreCLI@2
      displayName: 'Restore NuGet Packages'
      inputs:
        command: restore
        projects: '${{ parameters.pathToSolutionFolder }}/**/*.csproj'
        feedsToUse: 'select'
      continueOnError: true
        
    - task: DotNetCoreCLI@2
      displayName: 'Build Solution'
      inputs:
        command: 'build'
        projects: '${{ parameters.pathToSolutionFolder }}/**/*.csproj'
        arguments: '--configuration ${{ parameters.buildConfiguration }}'

    - task: DotNetCoreCLI@2
      displayName: 'Run Unit Tests'
      inputs:
        command: 'test'
        projects: '${{ parameters.pathToSolutionFolder }}/**/*Tests.csproj'
        arguments: '--configuration ${{ parameters.buildConfiguration }} --no-build --logger trx --collect:"XPlat Code Coverage"'
      continueOnError: true

    - task: PublishTestResults@2
      displayName: 'Publish Test Results'
      condition: succeededOrFailed()
      inputs:
        testResultsFormat: 'VSTest'
        testResultsFiles: '**/*.trx'
        mergeTestResults: true
        failTaskOnFailedTests: false

    - task: PublishCodeCoverageResults@2
      displayName: 'Publish Code Coverage'
      condition: succeededOrFailed()
      inputs:
        summaryFileLocation: '$(Agent.TempDirectory)/**/*coverage.cobertura.xml'
        failIfCoverageEmpty: false

  - job: ValidateDockerBuild
    displayName: 'Validate Docker Build'
    dependsOn: 
    - ValidateDotNetService
    condition: or(succeeded(), eq('${{ parameters.serviceType }}', 'python'))
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: 'Docker Build (Validation Only)'
      inputs:
        command: 'build'
        dockerfile: '${{ parameters.pathToSolutionFolder }}/Dockerfile'
        buildContext: ${{ parameters.buildContext }}
        tags: 'pr-validation-$(Build.BuildId)'

  - job: PRValidationSummary
    displayName: 'PR Validation Summary'
    dependsOn:
    - ValidateDockerBuild
    condition: succeededOrFailed()
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - bash: |
        echo "✅ PR Validation Complete"
        echo "- Build: Completed"
        echo "- Tests: Ran"
        echo "- Docker: Validated"
        echo ""
        echo "This PR has been validated and can be reviewed for merge."
      displayName: 'Validation Summary'
