# Backend API Pipeline - Monorepo Structure
# Supports GitFlow deployment strategy with PR validation and branch-based deployments

name: BackendAPI-$(Date:yyyyMMdd)$(Rev:.r)

# PR Validation - runs on PRs to protected branches
pr:
  branches:
    include:
    - dev
    - qa
    - staging
    - main
  paths:
    include:
    - services/backend-api/**
    - .pipeline-templates/**
    - shared/helm-charts/plain-app-chart/**

# CI/CD Trigger - runs when code is merged to these branches
trigger:
  branches:
    include:
    - dev
    - qa
    - staging
    - main
  paths:
    include:
    - services/backend-api/**
    - shared/helm-charts/plain-app-chart/**

variables:
  solutionName: 'BackendApi'
  pathToSolutionFolder: 'services/backend-api'
  buildContext: 'services/backend-api'
  releaseName: 'backend-api'
  acrUrl: 'mytestacr690.azurecr.io'  # UPDATE THIS
  acrServiceConnection: 'my-acr-connection'  # UPDATE THIS
  buildConfiguration: 'Release'

stages:
# ============================================
# PR VALIDATION STAGE - Only for PRs
# ============================================
- ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
  - template: /.pipeline-templates/pr-validation-template.yml
    parameters:
      solutionName: $(solutionName)
      pathToSolutionFolder: $(pathToSolutionFolder)
      buildContext: $(buildContext)
      buildConfiguration: $(buildConfiguration)

# ============================================
# BUILD AND TEST STAGE - Only on merges
# ============================================
- ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
  - template: /.pipeline-templates/build-and-test.yml
    parameters:
      pathToSolutionFolder: $(pathToSolutionFolder)
      buildConfiguration: $(buildConfiguration)

# ============================================
# DOCKER BUILD AND PUSH - Only on merges
# ============================================
- ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
  - template: /.pipeline-templates/docker-build-push.yml
    parameters:
      pathToSolutionFolder: $(pathToSolutionFolder)
      buildContext: $(buildContext)
      releaseName: $(releaseName)
      environment: dev
      acrUrl: $(acrUrl)
      acrServiceConnection: $(acrServiceConnection)

# ============================================
# HELM DEPLOY TO DEV - Only on merges
# ============================================
- ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
  - template: /.pipeline-templates/helm-deploy.yml
    parameters:
      releaseName: $(releaseName)
      environment: dev
      pathToSolutionFolder: $(pathToSolutionFolder)
      acrUrl: $(acrUrl)
      k8sServiceConnection: 'aks-dev-connection'  # UPDATE THIS
      requiresApproval: false

# ============================================
# HELM DEPLOY TO QA - Only on merges
# ============================================
- ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
  - template: /.pipeline-templates/helm-deploy.yml
    parameters:
      releaseName: $(releaseName)
      environment: qa
      pathToSolutionFolder: $(pathToSolutionFolder)
      acrUrl: $(acrUrl)
      k8sServiceConnection: 'aks-qa-connection'  # UPDATE THIS
      requiresApproval: false

# ============================================
# HELM DEPLOY TO STAGING - Only on merges
# ============================================
- ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
  - template: /.pipeline-templates/helm-deploy.yml
    parameters:
      releaseName: $(releaseName)
      environment: staging
      pathToSolutionFolder: $(pathToSolutionFolder)
      acrUrl: $(acrUrl)
      k8sServiceConnection: 'aks-staging-connection'  # UPDATE THIS
      requiresApproval: false

# ============================================
# HELM DEPLOY TO PRODUCTION - Only on merges
# ============================================
- ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
  - template: /.pipeline-templates/helm-deploy.yml
    parameters:
      releaseName: $(releaseName)
      environment: prod
      pathToSolutionFolder: $(pathToSolutionFolder)
      acrUrl: $(acrUrl)
      k8sServiceConnection: 'aks-prod-connection'  # UPDATE THIS
      requiresApproval: true
