apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: csi-secrets-store-provider-azure
  namespace: kube-system
  labels:
    app: csi-secrets-store-provider-azure
spec:
  selector:
    matchLabels:
      app: csi-secrets-store-provider-azure
  template:
    metadata:
      labels:
        app: csi-secrets-store-provider-azure
    spec:
      containers:
        - name: provider-azure
          image: mcr.microsoft.com/oss/azure/secrets-store/provider-azure:v1.6.2
          imagePullPolicy: IfNotPresent
          args:
            - "--endpoint=$(CSI_ENDPOINT)"
          env:
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
          volumeMounts:
            - name: providerdir
              mountPath: /providers
            - name: csi-socket-dir
              mountPath: /csi
      volumes:
        - name: providerdir
          hostPath:
            path: /etc/kubernetes/secrets-store-csi-providers
            type: DirectoryOrCreate
        - name: csi-socket-dir
          hostPath:
            path: /var/lib/kubelet/plugins/csi-secrets-store
            type: DirectoryOrCreate
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
        - operator: Exists