trigger:
    paths:
        include:
            - 'plain-app-chart'
            - 'helm-buildpipeline.yml'
steps:
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'plain-app-chart'
    includeRootFolder: true
    archiveType: 'tar'
    archiveFile: '$(Build.ArtifactStagingDirectory)/helm.tar.gz'
    replaceExistingArchive: true
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/helm.tar.gz'
    ArtifactName: 'drop'
    publishLocation: 'Container'
