trigger:
  branches:
    include:
      - main
  paths:
    include:
      - /Framework/Microservices/LegacyApi
      - /service-deployment-template.yml
      - /HelmCharts/plain-app-chart

pool:
  vmImage: 'windows-latest'

extends:
  template: /service-deployment-template.yml
  parameters:
    solutionName: MyCAI.Framework.Microservices.LegacyApi
    pathToSolutionFolder: Framework/Microservices/LegacyApi
    releaseName: legacyapimicroservice
    buildContext: Framework
    secureYml: mycai-legacy-values.yml
