trigger:
  branches:
    include:
      - main
  paths:
    include:
      - /Apps/Maestro/Api/MyCAI.Apps.Maestro.Api
      - /service-deployment-template.yml
      - /HelmCharts/plain-app-chart

pool:
  vmImage: 'windows-latest'

extends:
  template: /service-deployment-template.yml
  parameters:
    solutionName: MyCAI.Apps.Maestro.Api
    pathToSolutionFolder: Apps/Maestro/Api
    releaseName: mycaimaestroapi
    buildContext: Apps/Maestro/Api/MyCAI.Apps.Maestro.Api
    secureYml: mycai-maestroApi-values.yml
