trigger:
  branches:
    include:
      - main
  paths:
    include:
      - /Framework/Microservices/Resources
      - /service-deployment-template.yml
      - /HelmCharts/plain-app-chart

pool:
  vmImage: 'windows-latest'

extends:
  template: /service-deployment-template.yml
  parameters:
    solutionName: Resources
    pathToSolutionFolder: Framework/Microservices
    releaseName: resourcesmicroservice
    buildContext: Framework/Microservices/Resources
    secureYml: mycai-resources-values.yml
