trigger:
  branches:
    include:
      - main
  paths:
    include:
      - Framework/Microservices/Vectorization
      - /python-service-deployment-template.yml
      - /HelmCharts/plain-app-chart

pool:
  vmImage: 'windows-latest'

extends:
  template: /python-service-deployment-template.yml
  parameters:
    solutionName: Vectorization
    pathToFolder: Framework/Microservices
    releaseName: vectorizationmicroservice
    buildContext: Framework/Microservices/Vectorization
    secureYml: mycai-vectorization-values.yml
