# Frontend API Pipeline - Monorepo Structure
# Supports GitFlow deployment strategy with PR validation and branch-based deployments

name: FrontendAPI-$(Date:yyyyMMdd)$(Rev:.r)

# PR Validation - runs on PRs to protected branches
pr:
  branches:
    include:
    - dev
    - qa
    - staging
    - main
  paths:
    include:
    - services/frontend-api/**
    - .pipeline-templates/**
    - shared/helm-charts/plain-app-chart/**

# CI/CD Trigger - runs when code is merged to these branches
trigger:
  branches:
    include:
    - dev
    - qa
    - staging
    - main
  paths:
    include:
    - services/frontend-api/**
    - shared/helm-charts/plain-app-chart/**

variables:
  solutionName: 'FrontendApi'
  pathToSolutionFolder: 'services/frontend-api'
  buildContext: 'services/frontend-api'
  releaseName: 'frontend-api'
  acrUrl: 'mytestacr690.azurecr.io'  # UPDATE THIS
  acrServiceConnection: 'my-acr-connection'  # UPDATE THIS
  buildConfiguration: 'Release'

stages:
# ============================================
# PR VALIDATION STAGE
# ============================================
- template: /.pipeline-templates/pr-validation-template.yml
  parameters:
    solutionName: $(solutionName)
    pathToSolutionFolder: $(pathToSolutionFolder)
    buildContext: $(buildContext)
    buildConfiguration: $(buildConfiguration)

# ============================================
# BUILD AND TEST STAGE (Only on merges to branches)
# ============================================
- template: /.pipeline-templates/build-and-test.yml
  parameters:
    pathToSolutionFolder: $(pathToSolutionFolder)
    buildConfiguration: $(buildConfiguration)

# ============================================
# DOCKER BUILD AND PUSH (Only on merges to branches)
# ============================================
- template: /.pipeline-templates/docker-build-push.yml
  parameters:
    pathToSolutionFolder: $(pathToSolutionFolder)
    buildContext: $(buildContext)
    releaseName: $(releaseName)
    environment: dev
    acrUrl: $(acrUrl)
    acrServiceConnection: $(acrServiceConnection)

# ============================================
# HELM DEPLOY TO DEV
# ============================================
- template: /.pipeline-templates/helm-deploy.yml
  parameters:
    releaseName: $(releaseName)
    environment: dev
    pathToSolutionFolder: $(pathToSolutionFolder)
    acrUrl: $(acrUrl)
    k8sServiceConnection: 'aks-dev-connection'  # UPDATE THIS
    requiresApproval: false

# ============================================
# HELM DEPLOY TO QA
# ============================================
- template: /.pipeline-templates/helm-deploy.yml
  parameters:
    releaseName: $(releaseName)
    environment: qa
    pathToSolutionFolder: $(pathToSolutionFolder)
    acrUrl: $(acrUrl)
    k8sServiceConnection: 'aks-qa-connection'  # UPDATE THIS
    requiresApproval: false

# ============================================
# HELM DEPLOY TO STAGING
# ============================================
- template: /.pipeline-templates/helm-deploy.yml
  parameters:
    releaseName: $(releaseName)
    environment: staging
    pathToSolutionFolder: $(pathToSolutionFolder)
    acrUrl: $(acrUrl)
    k8sServiceConnection: 'aks-staging-connection'  # UPDATE THIS
    requiresApproval: false

# ============================================
# HELM DEPLOY TO PRODUCTION
# ============================================
- template: /.pipeline-templates/helm-deploy.yml
  parameters:
    releaseName: $(releaseName)
    environment: prod
    pathToSolutionFolder: $(pathToSolutionFolder)
    acrUrl: $(acrUrl)
    k8sServiceConnection: 'aks-prod-connection'  # UPDATE THIS
    requiresApproval: true
